### ISSUE TITLE
Discordance by using other language on project

### ISSUE THREAD

**Issue by fagnersales** [pedroreeis/fivem-web-dashboard#1]
I think you should keep using **English** as your main language while doing the code, because it doesn't make any sense, the usage of an other language, since all the code syntax is focused in one language (English). It won't make your code more readable by using your native language on parameters/variables for example, instead of that, it'll get way more confuse.

Imagine a situation, where your method says `doSomethingCool` while the result of the method is `resultadoDeAlgoLegal`, it doesn't really match, as you can see.

The same is valid for your routes, you're using `/success` _(actually you wrote `/sucess` which is wrong)_ an English name route, and also sometimes you use both languages _EN & PT-BR_ at `/unbanir`, which `un` is an English prefix for opposition and `banir` is a Portuguese word, it might be better as: `unban` or just `desbanir`.

So, my advice for you is just focus in English, since you're a developer, you probably realized that most of all content comes in English first and maybe after Portuguese, so as fast as you learn it, better will be. I can help if you want =)

**Comment by pedroreeis** [comment]
Hi Rafael, this project was a test, in the future I will update it and
leave open source on github. Thank you very much for the tip, the routes
were made for testing and not at the end. Thank you very much!!! missing
You.

Em sex, 19 de fev de 2021 08:47, Fagner Sales <notifications@github.com>
escreveu:

**Comment by fagnersales** [comment]
So, feel free to invite me on the next project! (And it's Fagner, lol)
